import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { redirect } from "next/navigation";
import { SkeletonTheme } from "react-loading-skeleton";

const firaSans = Fira_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Flipy - Flashcards",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="hu">
      <body className={`${firaSans.className} bg-background h-screen`}>
        {<SkeletonTheme baseColor="#202020" highlightColor="#444">
          {children}
        </SkeletonTheme>}
      </body>
    </html>
  );
}
